### ISSUE TITLE
What next ?

### ISSUE THREAD

**Issue by Dhavalu585** [tal95shah/LinkedIn_Scraper#2]
Able to open linkedin.com I used the below code to open

import webbrowser

new=2

url="http://www.linkedin.com"

webbrowser.open(url, new=new)

after this, I am able to open linkedin.com. But what next, I am not getting request page to key in Keyword and location...

Could you please help

**Comment by Dhavalu585** [comment]
error is -

line 65, in <module>
    email_button = driver.find_element_by_xpath('//input[@id="login-email"]')
NameError: name 'driver' is not defined

**Comment by tal95shah** [comment]
Hey Dhavalu! Kindly install ChromeDriver as I have mentioned in the instructions. I hope it will resolve your issue.
